// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getSORC
Rcpp::DataFrame getSORC(Rcpp::CharacterVector cnvInfo);
RcppExport SEXP _SOR_getSORC(SEXP cnvInfoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type cnvInfo(cnvInfoSEXP);
    rcpp_result_gen = Rcpp::wrap(getSORC(cnvInfo));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SOR_getSORC", (DL_FUNC) &_SOR_getSORC, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_SOR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
